class Customer {
  var id,
      userId,
      temporaryUserId,
      customerCustomNo,
      firstname,
      lastname,
      phoneNo,
      email,
      birthdate,
      address,
      profilePicture,
      adharcard,
      adharcardBack,
      pancard,
      votercard,
      createdBy,
      gender,
      allowSms,
      status,
      otp,
      apiToken,
      deviceToken,
      deviceId,
      deviceDetails,
      deviceId1,
      deviceId1Details,
      deviceId2,
      deviceId2Details,
      verifiedByAdmin,
      createdAt,
      updatedAt;

  Customer({
    required this.id,
    required this.userId,
    required this.temporaryUserId,
    required this.customerCustomNo,
    required this.firstname,
    required this.lastname,
    required this.phoneNo,
    required this.email,
    required this.birthdate,
    required this.address,
    required this.profilePicture,
    required this.adharcard,
    required this.adharcardBack,
    required this.pancard,
    required this.votercard,
    required this.createdBy,
    required this.gender,
    required this.allowSms,
    required this.status,
    required this.otp,
    required this.apiToken,
    required this.deviceToken,
    required this.deviceId,
    required this.deviceDetails,
    required this.deviceId1,
    required this.deviceId1Details,
    required this.deviceId2,
    required this.deviceId2Details,
    required this.verifiedByAdmin,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Customer.fromJson(Map<String, dynamic> json) {
    return Customer(
      id: json['id'] ?? '',
      userId: json['user_id'] ?? '',
      temporaryUserId: json['temporary_user_id'] ?? '',
      customerCustomNo: json['customer_custom_no'] ?? '',
      firstname: json['firstname'] ?? '',
      lastname: json['lastname'] ?? '',
      phoneNo: json['phone_no'] ?? '',
      email: json['email'] ?? '',
      birthdate: json['birthdate'] ?? '',
      address: json['address'] ?? '',
      profilePicture: json['profile_picture'] ?? '',
      adharcard: json['adharcard'] ?? '',
      adharcardBack: json['adharcard_back'] ?? '',
      pancard: json['pancard'] ?? '',
      votercard: json['votercard'] ?? '',
      createdBy: json['created_by'] ?? '',
      gender: json['gender'] ?? '',
      allowSms: json['allow_sms'] ?? '',
      status: json['status'] ?? '',
      otp: json['otp'] ?? '',
      apiToken: json['api_token'] ?? '',
      deviceToken: json['device_token'] ?? '',
      deviceId: json['device_id'] ?? '',
      deviceDetails: json['device_details'] ?? '',
      deviceId1: json['device_id_1'] ?? '',
      deviceId1Details: json['device_id_1_details'] ?? '',
      deviceId2: json['device_id_2'] ?? '',
      deviceId2Details: json['device_id_2_details'] ?? '',
      verifiedByAdmin: json['verified_by_admin'] ?? '',
      createdAt: json['created_at'] ?? '',
      updatedAt: json['updated_at'] ?? '',
    );
  }
}
