// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      /*case TargetPlatform.macOS:
        return macos;*/
      case TargetPlatform.windows:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYOE5J20wOLt3LrIQVSain-1SZDKK4jok',
    appId: '1:706778879884:android:3032464bfe8ec6d0c568a9',
    messagingSenderId: '706778879884',
    projectId: 'bachat-book',
    storageBucket: 'bachat-book.firebasestorage.app',
  );
  /*databaseURL: 'https://spsg-7c007-default-rtdb.firebaseio.com',*/

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYOE5J20wOLt3LrIQVSain-1SZDKK4jok',
    appId: '1:706778879884:android:3032464bfe8ec6d0c568a9',
    messagingSenderId: '706778879884',
    projectId: 'bachat-book',
    storageBucket: 'bachat-book.appspot.com',
    iosBundleId: 'com.bachat_book',
  );
}
